		------------------------
		---CONEXAO COM O DW-----
		------------------------

		USE COMERCIO_DW
		GO

		------------------------
		--CRIAÇAO DA PROCEDURE--
		------------------------

		CREATE PROC CARGA_FATO
		AS

		DECLARE @FINAL DATETIME 
		DECLARE	@INICIAL DATETIME
		
		SELECT  @FINAL = MAX(DATA)
		FROM COMERCIO_DW.DBO.DIM_TEMPO T

		SELECT @INICIAL = MAX(DATA)
			FROM COMERCIO_DW.DBO.FATO FT
			JOIN COMERCIO_DW.DBO.DIM_TEMPO T ON (FT.ID_TEMPO=T.SKTEMPO)

		IF @INICIAL IS NULL
		BEGIN
			SELECT @INICIAL = MIN(DATA)
			FROM COMERCIO_DW.DBO.DIM_TEMPO T
		END

		INSERT INTO COMERCIO_DW.DBO.FATO(
			ID_NOTA ,
			ID_CLIENTE ,
			ID_VENDEDOR ,
			ID_FORMA ,
			ID_FORNECEDOR,
			ID_PRODUTO,
			ID_TEMPO,
			QUANTIDADE,
			TOTAL_ITEM,
			CUSTO_TOTAL,
			LUCRO_TOTAL )
		SELECT
			N.SKNOTA AS ID_NOTA,
			C.SKCLIENTE AS ID_CLIENTE,
			V.SKVENDEDOR AS ID_VENDEDOR,
		   FO.SKFORMA AS ID_FORMA,
		   FN.SKFORNECEDOR AS ID_FORNECEDOR,
			P.SKPRODUTO AS ID_PRODUTO,	
			T.SKTEMPO as ID_TEMPO,
			F.QUANTIDADE,
			F.TOTAL_ITEM,
			F.CUSTO_TOTAL,
			F.LUCRO_TOTAL
	
		FROM
			COMERCIO_STAGE.DBO.ST_FATO F

			INNER JOIN DBO.DIM_FORMA FO
			on (F.ID_FORMA_PAGAMENTO=FO.IDFORMA)	 

			INNER JOIN DBO.DIM_NOTA N
			on (F.ID_NOTA_FISCAL=N.IDNOTA)

				INNER JOIN DBO.DIM_FORNECEDOR FN
			on (F.ID_FORNECEDOR=FN.IDFORNECEDOR
				AND (FN.INICIO <= F.DATA_VENDA AND (FN.FIM >= F.DATA_VENDA) or (FN.FIM IS NULL)))

			INNER JOIN DBO.DIM_CLIENTE C
			on (F.ID_CLIENTE=C.IDCLIENTE
				AND (C.INICIO <= F.DATA_VENDA
				AND (C.FIM >= F.DATA_VENDA) or (C.FIM IS NULL)))

				INNER JOIN DBO.DIM_VENDEDOR V
			on (F.ID_VENDEDOR=V.IDVENDEDOR
				AND (V.INICIO <= F.DATA_VENDA
				AND (V.FIM >= F.DATA_VENDA) or (V.FIM IS NULL)))

				INNER JOIN DBO.DIM_PRODUTO P
			ON (F.ID_PRODUTO=P.IDPRODUTO 
			AND (P.INICIO <= F.DATA_VENDA 
			AND (P.FIM >= F.DATA_VENDA) OR (P.FIM IS NULL)))
			INNER JOIN DBO.DIM_TEMPO T
			ON (CONVERT(VARCHAR, T.DATA,102) = CONVERT(VARCHAR,
			F.DATA_VENDA,102))
			--WHERE F.DATA > @INICIAL AND F.DATA < @FINAL
			WHERE F.DATA_VENDA BETWEEN @INICIAL AND @FINAL
GO










