USE COMERCIO_DW
GO

CREATE TABLE DIM_CLIENTE
(
	SKCLIENTE INT PRIMARY KEY IDENTITY,
	IDCLIENTE INT,
	INICIO DATETIME,
	FIM DATETIME,
	NOME VARCHAR(100),
	SEXO VARCHAR(20),
	EMAIL VARCHAR(100),
	NASCIMENTO DATE,
	CIDADE VARCHAR(100),
	ESTADO VARCHAR(30),
	REGIAO VARCHAR(30)
)
GO
CREATE TABLE DIM_NOTA
(
	SKNOTA INT PRIMARY KEY IDENTITY,
	IDNOTA INT
)
GO
CREATE TABLE DIM_FORMA
(
	SKFORMA INT PRIMARY KEY IDENTITY,
	IDFORMA INT, 
	NOME VARCHAR(50)
)
GO
CREATE TABLE DIM_TEMPO
(
	SKTEMPO INT PRIMARY KEY IDENTITY,
	DATA DATE,
	DIA CHAR(2),
	DIA_SEMANA VARCHAR(10),
	MES CHAR(2),
	NOME_MES VARCHAR(20),
	QUARTO TINYINT,
	NOMEQUARTO VARCHAR(20),
	ANO CHAR(4),
	ESTACAO_ANO VARCHAR(20),
	FIM_SEMANA CHAR(3),
	DATA_COMPLETA VARCHAR(10)
)
GO

CREATE TABLE DIM_VENDEDOR
(
	SKVENDEDOR INT PRIMARY KEY IDENTITY,
	IDVENDEDOR INT,
	IDGERENTE INT,
	INICIO DATETIME,
	FIM DATETIME,
	NOME VARCHAR(100),
	SEXO VARCHAR(20)
)
GO
CREATE TABLE DIM_FORNECEDOR
(
	SKFORNECEDOR INT PRIMARY KEY IDENTITY,
	IDFORNECEDOR INT,
	INICIO DATETIME,
	FIM DATETIME,
	NOME VARCHAR(100)
)
GO
CREATE TABLE CATEGORIA
(
	IDCATEGORIA INT PRIMARY KEY,
	NOME VARCHAR(100)
)
GO
CREATE TABLE DIM_PRODUTO
(
	SKPRODUTO INT PRIMARY KEY IDENTITY,
	IDPRODUTO INT,
	INICIO DATETIME,
	FIM DATETIME, 
	NOME VARCHAR(100),
	VALOR_UNITARIO NUMERIC(10,2),
	CUSTO_MEDIO NUMERIC(10,2),
	ID_CATEGORIA INT,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
)
GO

DROP TABLE FATO
TRUNCATE TABLE DIM_TEMPO
CREATE TABLE FATO
(
	ID_CLIENTE INT  REFERENCES DIM_CLIENTE(SKCLIENTE),
	ID_TEMPO INT REFERENCES DIM_TEMPO(SKTEMPO),
	ID_PRODUTO INT REFERENCES DIM_PRODUTO(SKPRODUTO),
	ID_VENDEDOR INT REFERENCES DIM_VENDEDOR(SKVENDEDOR),
	ID_FORNECEDOR INT REFERENCES DIM_FORNECEDOR(SKFORNECEDOR),
	ID_FORMA INT REFERENCES DIM_FORMA(SKFORMA),
	ID_NOTA INT REFERENCES DIM_NOTA(SKNOTA),
	QUANTIDADE INT,
	TOTAL_ITEM NUMERIC(10,2),
	CUSTO_TOTAL NUMERIC(10,2),
	LUCRO_TOTAL NUMERIC(10,2)
)
GO
