/*
RELATIONAL -> STAGE AREA -> DW

MODELO RELATIONAL 

*/
CREATE DATABASE COMERCIO_OLTP
GO

USE COMERCIO_OLTP
GO

CREATE TABLE ENDERECO
(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	ID_CLIENTE INT UNIQUE, 
	RUA VARCHAR(100) NOT NULL,
	CIDADE VARCHAR (100) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	REGIAO VARCHAR (20) NOT NULL
);
GO

CREATE TABLE VENDEDOR
(
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	IDVENDEDOR INT PRIMARY KEY IDENTITY,
);
GO

CREATE TABLE CATEGORIA
(
	IDCATEGORIA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (50) NOT NULL
);
GO 

CREATE TABLE FORNECEDOR
(
	IDFORNECEDOR INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50)
);
GO

DROP TABLE PRODUTO
CREATE TABLE PRODUTO
(
	IDPRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	CUSTO_MEDIO NUMERIC(10,2),
	ID_CATEGORIA INT,
	ID_FORNECEDOR INT
);
GO

CREATE TABLE FORMA_PAGAMENTO
(
	IDFORMA_PAGAMENTO INT PRIMARY KEY IDENTITY,
	FORMA VARCHAR(40)
);
GO
CREATE TABLE NOTA_FISCAL
(
	IDNOTA_FISCAL INT PRIMARY KEY IDENTITY,
	ID_FORMA_PAGAMENTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_VENDEDOR INT NOT NULL, 
	DATA_NOTA DATE,
	TOTAL NUMERIC(10,2)
);
GO
CREATE TABLE ITEM_NOTA_FISCAL
(
	IDITEM_NOTA_FISCAL INT PRIMARY KEY IDENTITY,
	ID_NOTA_FISCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE NUMERIC(10,2)
);
GO
CREATE TABLE CLIENTE 
(
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (30),
	SOBRENOME VARCHAR (30),
	EMAIL VARCHAR(50),
	SEXO CHAR(1),
	NASCIMENTO DATE
);
GO
